name: CI

on:
  release:
    types:
      - published
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z]+[0-9]+)?
  pull_request:
    paths-ignore:
      - ".github/**"
    types:
      - opened
      - synchronize

# This ensures that previous jobs for the workflow are canceled when the ref is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          LTAG=$(make image-lversion)
          BTAG=$(make image-bversion)
          TAGS="${LTAG},${BTAG}"
          echo ::set-output name=tags::${TAGS}

      - name: Cache Docker layers
        uses: actions/cache@v2.1.7
        continue-on-error: true
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: |
            buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
