name: Codeowners

on:
  pull_request:
    paths-ignore:
      - "**/CODEOWNERS"

# This ensures that previous jobs for the workflow are canceled when the ref is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    # only apply on unmerged pull requests
    if: github.event.pull_request.merged_by == '' && github.actor != 'dependabot[bot]'
    timeout-minutes: 10
    steps:
      - name: checkout code
        uses: actions/checkout@v2.4.0
        with:
          # the fetch depth 0 (=all) is important
          fetch-depth: 0
      - name: update code owners
        uses: gofunky/update-codeowners@v0.3.2
        with:
          distribution: 75
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: check file
        run: cat .github/CODEOWNERS

      - name: Commit and push
        uses: test-room-7/action-update-file@v1.6.0
        with:
          commit-msg: "[skip ci] Updated CODEOWNERS"
          file-path: ".github/CODEOWNERS"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
